# Generated by Django 2.1.7 on 2019-02-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoservice',
            old_name='id_autoservice',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='id_client',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='id_autoservice',
            new_name='autoservice',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='id_offer',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='id_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='id_request',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='id_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='id_service',
            new_name='id',
        ),
        migrations.AddField(
            model_name='offer',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='autoservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Autoservice', to_field='id_autoservice'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Service', to_field='id_service'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Client', to_field='id_client'),
        ),
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Service', to_field='id_service'),
        ),
        migrations.AlterModelTable(
            name='autoservice',
            table='autoservice',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='offer',
            table='offer',
        ),
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
